### PR TITLE
Changed text file for LGPL 3

### PR DESCRIPTION
**Pull request by arpitar**
made appropriate changes for lgpl3 text file

### CODE REVIEW

**Comment by samchrisinger** [comment]
@arpitar looks like the file name is wrong (index**x**). Can you please fix and I will merge?

**Comment by samchrisinger** [comment]
Actually, looking at the commit message this was intentional. Can you please explain?

**Comment by arpitar** [comment]
Hello Sam,

Actually the text of the licenses being displayed were same for LGPL 2 and LGPL 3, hence I had to make a change to make sure they display their respective contents. Is there any change in their behavior?

**Comment by samchrisinger** [comment]
Ok, understood. I'm just confused about why the index file was renamed. Any changes to the license names can be made directly in that file.

**Comment by arpitar** [comment]
Could you tell me which index file was renamed and what was it renamed to?
Are you referring to the list-of-licenses file?

**Comment by samchrisinger** [comment]
This commit adds a new file `indexx.js`, when I would have expected edits to the existing `index.js`

**Comment by arpitar** [comment]
I was trying to fork a copy of your index file and make changes to it instead of making changes to your file, and then merging if it worked. I think that’s why I had sent you the pull request. Would you be making the changes to the file internally now?

**Comment by samchrisinger** [comment]
It would be easiest for me if you would:
- make whatever changes are needed to `index.js`
- commit those changes
- either updated this PR, or close this one and open another

**Comment by notslang** [comment]
:-1: for switching to `require('raw!...')`. That's non-standard (doesn't work with node) and means that importing this module will make 19 separate file system calls, rather than the 1 call that it does right now, after you've built the module.

**Pull request closed without merging**
